import type { Metadata } from "next";
import {  Montserrat } from "next/font/google";
import {twMerge}from "tailwind-merge"
import "./globals.css";
import { Header } from "@/sections/Header";
import Footer from "./footer/page";
import Chatbot from "@/components/Chatbot";
import SocialLinks from "@/components/SocialLinks";


const roboto=Montserrat({subsets:["latin"],variable:"--font-sans",weight: [ "100", "300","400", "500", "700"],});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ twMerge( roboto.variable,"bg-gray-900 text-white antialiased font-sans")}>
        <Header/>
        {children}
        <Footer/>
         <SocialLinks/>
        <Chatbot/>
      </body>
    </html>
  );
}
